language: csharp
solution: SharpiesMafia.sln
os: osx
mono: none
sudo: required
dist: xenial
dotnet: 2.2.300
install:
  - dotnet restore ./SharpiesMafia.sln
script:
 - dotnet restore
 - dotnet build
 - dotnet test ./SharpiesMafia.Tests/SharpiesMafia.Tests.csproj --filter TestCategory!=OPTIONAL-TEST
after_script:
    - dotnet test ./SharpiesMafia.Tests/SharpiesMafia.Tests.csproj --filter TestCategory=OPTIONAL-TEST
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    - aws ecr get-login --region us-west-2 --no-include-email
    - aws lambda invoke --function-name SharpiesMafia-travis --region us-west-2 --payload '{"Build_Id":"'"$TRAVIS_JOB_ID"'", "Travis_Branch":"'"$TRAVIS_BRANCH"'", "Travis_Test_Result":"'"$TRAVIS_TEST_RESULT"'", "Travis_Commit":"'"$TRAVIS_COMMIT"'", "Travis_Repo_Slug":"'"$TRAVIS_REPO_SLUG"'", "Travis_Pull_Request":"'"$TRAVIS_PULL_REQUEST"'"}' outputfile
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
...
